# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dh" do |dh|
    dh.vm.box = "bento/ubuntu-18.10"
	dh.vm.provision "shell", path: "docker.sh"
	dh.vm.network "public_network", ip: "192.168.0.18"
    dh.vm.network "forwarded_port", guest: 8080, host: 8081
  end
end
