---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address={{ node_ip }} --apiserver-cert-extra-sans={{ node_ip }}  --node-name {{inventory_hostname}} --pod-network-cidr=192.168.0.0/16

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  
- name: Setup kubeconfig for {{ inventory_hostname }} user
  command: "{{ item }}"
  with_items:
  - mkdir -p /home/{{ inventory_hostname }}/.kube
  - cp -i /etc/kubernetes/admin.conf /home/{{ inventory_hostname }}/.kube/config
  - chown {{ inventory_hostname }}:{{ inventory_hostname }} /home/{{ inventory_hostname }}/.kube/config

- name: Install calico pod network
  become: false
  command: kubectl create -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml


- name: Apply kube flannel
  become: false
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml

- name: Add kuberneters bashboard
  become: false
  command: "{{ item }}"
  with_items:
  - kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
  - kubectl create serviceaccount dashboard -n default
  - kubectl create clusterrolebinding bashboard-admin -n default --clusterrole=cluster-admin --serviceaccount=default:dashboard